name: Build Astro Project with Bun

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: Build Astro project
      run: bun run build

    - name: Deploy to `http` branch
      run: |
        # Configure Git user
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
        # Clone the `http` branch or create an empty orphan branch if it doesn't exist
        git fetch origin http || git checkout --orphan http

        # Clean the branch and copy the dist folder contents
        git reset --hard
        git clean -fd
        cp -r dist/* .

        # Commit the changes and push to the `http` branch
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push origin http --force
