name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.46.3"

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/deno
          key: ${{ runner.os }}-deno-cache-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-cache-

      - name: Build project
        run: deno task build # Runs the build task from deno.json

      - name: Checkout http branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout -B http

      - name: Copy files to http branch
        run: |
          rm -rf * # Clear the existing files in the http branch
          cp -R dist/* . # Copy files from the dist folder to the root

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Deploy updated files from dist"
          git push origin http --force
