name: Deno Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Cache npm dependencies (optional but recommended)
      - name: Cache NPM modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno/npm
          key: ${{ runner.os }}-deno-npm-${{ hashFiles('deno.json') }}
          restore-keys: |
            ${{ runner.os }}-deno-npm-

      # Install dependencies
      - name: Cache Deno modules
        run: deno cache --reload deno.json

      - name: Build with Astro
        run: deno task build
